# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'JSONParsingSimpleNonMVC' do
pod 'Alamofire', '~> 3.0'
end

target 'JSONParsingSimpleNonMVCTests' do

end

target 'JSONParsingSimpleNonMVCUITests' do

end

